### ISSUE TITLE
Use Zippopotamus (http://zippopotam.us/) to serve lat/lon when user declines geolocation

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-api#22]
I'd like to be able to send a 5 digit zip code to the API and get a long/lat back.  I looked at sending requests to Zippopotamus directly from the app, but their setup doesn't presently support JSONP.

**Comment by dogweather** [comment]
I'm pretty sure I've seen a public dataset with lat/lon's of the centers of zip codes.

**Comment by ttavenner** [comment]
This is pretty far outside the scope of the OHI api. If you are willing to use their plugin, SmartyStreets can fill this role and supports callbacks as part of an event response. I will DM you a key so you can test it out to see if that will work. Here is the documentation:

https://smartystreets.com/docs/plugin
